# Run Test Program

A test program has been created for you already. The program uses an API
(via the request library) to retrieve and print a random fact about
cats. If you wish to view the source code, use the following
command to print the content into the terminal:

[source,bash,run]
----
cat /home/api.py
----

To run the test program, make sure your environment is activated.

If your environment is not activated, reactivate it with the following
command:

[source,bash,run]
----
source /home/python/sampleenvironment/bin/activate
----

'''''

Now, run the test program by running the following command:

[source,bash,run]
----
python /home/api.py
----

You should see an output that contains a fact about a cat. This would
not be possible without the virtual environment that was just created.
To demonstrate why this would not work without the environment you set
up, run the following command to deactivate your environment and then
try running the program again. It will not be able to display a cat
fact, and will instead print an error message.

[source,bash,run]
----
deactivate
python /home/api.py
----
